# Generated by Django 3.1.6 on 2021-02-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField(auto_now_add=True)),
                ('quation', models.TextField()),
                ('ansewer', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tag', models.CharField(choices=[('機械学習', 'Machine Learning'), ('ディープラーニング', 'Deep Learning'), ('データ分析', 'Data Analysis'), ('Python 基礎', 'Python Basic')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
