# Generated by Django 3.1.6 on 2021-02-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='ansewer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='quizmodel',
            old_name='quation',
            new_name='question',
        ),
    ]
