# Generated by Django 3.1.6 on 2021-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoryPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
