# Generated by Django 3.1.6 on 2021-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoryPost', '0003_auto_20210215_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
